language: python
python:
  - "3.6"
cache: pip
install:
  - pip install tox-travis coveralls
script:
  - tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: "bdist_wheel"
  user: "__token__"
  password:
    secure: "QPgZE5kZNTLTXeZ5hzHi4ghYjVL+dDTCa4HNddrMZt2Z93fCU8cajzLsgYo+v2qVGf4rEgjuRbhhg5O52eB58SGjpF61hQ7zOxZ1rj/aqA3BcAPYahAvH8WJA8Ti+nFE/Ru7dUggDtIphsNyxGK/92yLBivIPuR2eabl6HCaqWoC1N3AfsXUkILz89BeEhE6xCoxdUTr+J53uq++6Ho24pS4xNcVRpZbQZt4LiG3ZsxodHLVlrXOeaC3/u2URPvKLJjulObZQSgsmCMiR0VdFK6D3lF+rggGqYrstB82rA0NASrPTVKrfEZxkF/6XHReG+At2L3b2M9NinyCNTifzEUg7EkbVZAhkpb4c6BTxjRczYh1duumFXZeBulb7VfSyULS4YkyYijGKBXFk7f1UwAprJa5cQWNKgezX7YWeZEsPQrMtzqjnbqBpvMtC25UtoHdlfpa97b0YWI1rHaNIcvqsW0cJdDmHm4cjK89lU93QS1KneYn2W09w5kvNKwsQH7fIW2o0WHEBseniPq84Gxt3ZgIOVP7v5+StspVw9fwYZZNw/WPFvL/2qKHM5BqoHhy/Pi2DXwhR5x2YtT3lsmGfi8KH1VnftLgkKv6DDcyNy1i9vay6/IY+dO3cbfONSjdfz8XJy3CscVVS6FEH47iuJOXFVsNEzueLr1gKI8="
  on:
    branch: master
  skip_existing: true
after_success:
- coveralls --verbose